name: Build

on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on:
      - windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --user pipx==1.2.0
          python -m pipx install poetry
          python -m pipx install poethepoet
          poetry install --with dev --no-root
      - name: mypy
        run: |-
            poe types
      - name: flake8
        run: |-
            poe lint
      - name: pytest
        run: |-
            poe test --junitxml=test_results/test.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: test_results/*.xml
        if: always()
