name: Build

on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: 
      - windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --user pipx==1.2.0
          python -m pipx install poetry==1.5.1
          python -m pipx install poethepoet==0.21.1
          poetry install --with dev --no-root
      - name: mypy
        run: |-
            set PATH=%PATH%;C:\Users\tfsbuild\.local\bin;C:\Users\tfsbuild\AppData\Roaming\Python\Python38\Scripts
            poe types
      - name: flake8
        run: |-
            set PATH=%PATH%;C:\Users\tfsbuild\.local\bin;C:\Users\tfsbuild\AppData\Roaming\Python\Python38\Scripts
            poe lint
      - name: pytest
        run: |-
            set PATH=%PATH%;C:\Users\tfsbuild\.local\bin;C:\Users\tfsbuild\AppData\Roaming\Python\Python38\Scripts
            poe test
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.12.0
        with:
            comment_title: Python ${{ env.python_version }}
            junit_files: "**/test-results.xml"
