name: CI

on:
  push:
    branches:
      - master
      - 'releases/**'
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  report_test_results:
    name: Report test results
    uses: ./.github/workflows/report_test_results.yml
    needs: [build]
    if: always()
